import { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";
export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          h-screen
          flex
          flex-col
          items-center
          justify-center
          ${inter.className}
        `}
      >
        {children}
      </body>
    </html>
  );
}
