import { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";
import { getUser } from "@/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  if (user) {
    redirect("/");
  }

  return (
    <html lang="en">
      <body
        className={`
          min-h-screen
          flex
          flex-col
          items-center
          justify-center
          ${inter.className}
        `}
      >
        {children}
      </body>
    </html>
  );
}
