import { FormInput } from "@/shared";
import { BackButton } from "../_components";
import Link from "next/link";

export const metadata = {
  title: "Register | Ecommerce Platform",
  description: "Generated by Next.js",
};

export default function Register() {
  return (
    <form
      className="
        min-w-[90vh]
        sm:min-w-[500px]
        md:min-w-[600px]
        border-[1px]
        border-black/20
        px-8
        flex
        flex-col
        gap-y-6
        py-6
      "
    >
      <div
        className="
          flex
          items-center
          gap-x-4
          justify-between
        "
      >
        <BackButton />
        <div>
          <a href="/">Logo</a>
        </div>
      </div>
      <div
        className="
          flex
          flex-col
          gap-y-8
        "
      >
        <FormInput
          name="email"
          type="email"
          placeholder="Enter your email here"
          withLabel
          labelName="Email"
        />
        <FormInput
          name="password"
          type="password"
          placeholder="Enter your password here"
          withLabel
          labelName="Password"
        />
      </div>
      <div
        className="
          flex
          items-center
          justify-center
          w-full
          gap-x-4
        "
      >
        <button
          className="
            bg-black
            text-white
            hover:bg-black/90
            py-2.5
            px-6
            transition
          "
        >
          Log In
        </button>
        <Link
          className="
            text-center
            hover:underline
          "
          href={"/login"}
        >
          New here? Register
        </Link>
      </div>
    </form>
  );
}
