import { Metadata } from "next";
import { RegisterForm } from "./_components";
import { BackButton } from "../_components";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Register | Ecommerce Platform",
  description: "Generated by Next.js",
};

export default function Register() {
  return (
    <main
      className="
        min-w-[90vh]
        sm:min-w-[500px]
        md:min-w-[600px]
        border-[1px]
        border-black/20
        px-8
        flex
        flex-col
        gap-y-6
        py-6
      "
    >
      <div
        className="
          flex
          items-center
          gap-x-4
          justify-between
        "
      >
        <BackButton />
        <div>
          <Link href="/">Logo</Link>
        </div>
      </div>
      <RegisterForm />
    </main>
  );
}
