"use client";

import { ImageSkeleton } from "@/shared";
import { useTransition } from "react";

export default function ProductLoading() {
  const [isPending] = useTransition();

  console.log(isPending);

  return (
    <main
      className="
        flex
        flex-col
        gap-y-10
      "
    >
      <section
        className="
          max-sm:mt-4
          flex
          w-full
          gap-x-8
          flex-col
          sm:flex-row
          gap-y-6
        "
      >
        <div
          className="
            mt-10
            sm:flex-[2]
            max-sm:h-[400px]
            max-md:h-[400px]
            max-lg:h-[500px]
            h-[600px]
            sm:grid
            sm:grid-cols-4
            sm:grid-rows-3
            sm:gap-4
          "
        >
          <ImageSkeleton
            className="
              col-start-2
              row-span-3
              h-full
              col-span-3
            "
          />
          <ImageSkeleton
            className="
              row-start-1
            "
          />
          <ImageSkeleton />
          <ImageSkeleton />
        </div>
        <div
          className="
            flex
            flex-col
          "
        >
          <div
            className="
              sm:mt-10
              sm:flex-[1]
              flex
              grow
              pb-20
              flex-col
              gap-y-6
            "
          >
            <div
              className="
                flex
                flex-col
                gap-y-2
              "
            >
              <h2
                className="
                  text-3xl
                  leading-normal
                  font-semibold
                  border-[3px]
                  border-gray-300
                  w-[200px]
                  animate-pulse
                "
              ></h2>
            </div>
            <div
              className="
                flex
                items-center
                gap-x-6
                text-lg
              "
            >
              <span
                className="
                  line-through
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  text-gray-400
                  animate-pulse
                "
              ></span>
              <span
                className="
                  font-bold
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  animate-pulse
                "
              ></span>
            </div>
            <p
              className="
                border-[3px]
                border-gray-300
                animate-pulse
                w-[100px]
              "
            ></p>
            <div
              className="
                flex
                flex-col
                gap-y-3
              "
            >
              <p
                className="
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  animate-pulse
                "
              ></p>
              <p
                className="
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  animate-pulse
                "
              ></p>
            </div>
          </div>
          <div
            className="
              sm:mt-10
              sm:flex-[1]
              flex
              grow
              pb-20
              flex-col
              gap-y-6
            "
          >
            <div
              className="
                flex
                flex-col
                gap-y-2
              "
            >
              <h2
                className="
                  text-3xl
                  leading-normal
                  font-semibold
                  border-[3px]
                  border-gray-300
                  w-[200px]
                  animate-pulse
                "
              ></h2>
            </div>
            <div
              className="
                flex
                items-center
                gap-x-6
                text-lg
              "
            >
              <span
                className="
                  line-through
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  text-gray-400
                  animate-pulse
                "
              ></span>
              <span
                className="
                  font-bold
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  animate-pulse
                "
              ></span>
            </div>
            <p
              className="
                border-[3px]
                border-gray-300
                animate-pulse
                w-[100px]
              "
            ></p>
            <div
              className="
                flex
                flex-col
                gap-y-3
              "
            >
              <p
                className="
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  animate-pulse
                "
              ></p>
              <p
                className="
                  border-[3px]
                  border-gray-300
                  w-[50px]
                  animate-pulse
                "
              ></p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
